<?php 

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('restaurants')->insert([
            [
                'id' => 1,
                'name' => 'Trattoria Roma',
                'description' => 'Auténtica comida italiana con ingredientes frescos.',
                'average_price' => 25.50,
                'photo' => 'italiana.jpg',
                'gerente_id' => 3,
                'location_id' => 1, 
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'El Mariachi',
                'description' => 'Sabores tradicionales de México con mariachi en vivo.',
                'average_price' => 20.00,
                'photo' => 'mexicana.jpg',
                'gerente_id' => 4,
                'location_id' => 2, 
                'rating' => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Sakura Sushi',
                'description' => 'Exquisita gastronomía japonesa con sushi y ramen.',
                'average_price' => 30.00,
                'photo' => 'japonesa.jpg',
                'gerente_id' => 5,
                'location_id' => 3, 
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Gran Muralla',
                'description' => 'Delicias de la cocina china en un ambiente tradicional.',
                'average_price' => 18.00,
                'photo' => 'china.jpg',
                'gerente_id' => 6,
                'location_id' => 4, 
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Mediterráneo Grill',
                'description' => 'Sabores frescos del mar y la tierra con un toque moderno.',
                'average_price' => 28.00,
                'photo' => 'mediterranea.jpg',
                'gerente_id' => 7,
                'location_id' => 5, 
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Curry House',
                'description' => 'Los mejores curries de la India con especias tradicionales.',
                'average_price' => 22.50,
                'photo' => 'india.jpg',
                'gerente_id' => 8,
                'location_id' => 6, 
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Le Petit Bistro',
                'description' => 'Un rincón acogedor de cocina francesa.',
                'average_price' => 35.00,
                'photo' => 'francesa.jpg',
                'gerente_id' => 9,
                'location_id' => 7, 
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Texas BBQ',
                'description' => 'Costillas y carnes ahumadas al mejor estilo tejano.',
                'average_price' => 27.00,
                'photo' => 'bbq.jpg',
                'gerente_id' => 10,
                'location_id' => 8, 
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Green Veggie',
                'description' => 'Opciones vegetarianas y veganas con mucho sabor.',
                'average_price' => 19.00,
                'photo' => 'vegetariana.jpg',
                'gerente_id' => 11,
                'location_id' => 9, 
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Bangkok Street',
                'description' => 'Comida callejera tailandesa en su máxima expresión.',
                'average_price' => 21.00,
                'photo' => 'tailandesa.jpg',
                'gerente_id' => 12,
                'location_id' => 10, 
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Seoul Kitchen',
                'description' => 'Lo mejor de la comida coreana, incluyendo bulgogi y kimchi.',
                'average_price' => 26.00,
                'photo' => 'coreana.jpg',
                'gerente_id' => 13,
                'location_id' => 11, 
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'La Taberna Española',
                'description' => 'Tapas y paellas con el auténtico sabor de España.',
                'average_price' => 24.00,
                'photo' => 'espanola.jpg',
                'gerente_id' => 14,
                'location_id' => 12, 
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
